// create a api with and and png path from google
const Sponsor = [
    {
        id: 1,
        name: "collab1.png",
        image: "img1.jpeg",
        alt: "google",
        link: "https://google.com",
        discription: "for signup",
    },
    {
        id: 2,
        name: "collab02.png",
        image: "img2.png",
        alt: "facebook",
        link: "https://facebook.com",
        discription: "for login",
    },
    {
        id: 3,
        name: "collab03.png",
        image: "img3.png",
        alt: "twitter",
        link: "https://twitter.com",
        discription: "for sharing",
    },
    {
        id: 4,
        name: "collab04.png",
        image: "img4.png",
        alt: "linkedin",
        link: "https://linkedin.com",
        discription: "for networking",
    },
    {
        id: 5,
        name: "collab05.png",
        image: "img5.png",
        alt: "github",
        link: "https://github.com",
        discription: "for code hosting",
    },
    {
        id: 6,
        name: "collab06.png",
        image: "img6.png",
        alt: "slack",
        link: "https://slack.com",
        discription: "for communication",
    },
    {
        id: 7,
        name: "collab1.png",
        image: "img7.png",
        alt: "dropbox",
        link: "https://dropbox.com",
        discription: "for storage",
    },
    {
        id: 8,
        name: "collab02.png",
        image: "img8.png",
        alt: "zoom",
        link: "https://zoom.us",
        discription: "for meetings",
    },
    {
        id: 9,
        name: "collab03.png",
        image: "img9.png",
        alt: "asana",
        link: "https://asana.com",
        discription: "for project management",
    },
    {
        id: 10,
        name: "collab04.png",
        image: "img10.png",
        alt: "trello",
        link: "https://trello.com",
        discription: "for task tracking",
    },
    {
        id: 11,
        name: "collab05.png",
        image: "img10.png",
        alt: "trello",
        link: "https://trello.com",
        discription: "for task tracking",
    },
    {
        id: 12,
        name: "collab06.png",
        image: "img10.png",
        alt: "trello",
        link: "https://trello.com",
        discription: "for task tracking",
    },
];

export default Sponsor;
